apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: herifauzan/simpleapp:latest
        ports:
        - containerPort: 8080
      
      
      